schema: src/client/lib/gql/schema.gql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:3000/api/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
